//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstallManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMachine
    {
        public ClientMachine()
        {
            this.Installations = new HashSet<Installation>();
        }
    
        public long ID { get; set; }
        public string ComputerName { get; set; }
    
        public virtual ICollection<Installation> Installations { get; set; }
    }
}
