//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InstallManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installation
    {
        public Installation()
        {
            this.InstallationItems = new HashSet<InstallationItem>();
            this.ClientMachines = new HashSet<ClientMachine>();
            this.Installation1 = new HashSet<Installation>();
            this.Installations = new HashSet<Installation>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string ExecutablePath { get; set; }
        public string RegistryPath { get; set; }
    
        public virtual ICollection<InstallationItem> InstallationItems { get; set; }
        public virtual ICollection<ClientMachine> ClientMachines { get; set; }
        public virtual ICollection<Installation> Installation1 { get; set; }
        public virtual ICollection<Installation> Installations { get; set; }
    }
}
